//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital.Forensic.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public string AdminSurname { get; set; }
        public string AdminFirstname { get; set; }
        public string AdminMiddlename { get; set; }
        public string AdminUsername { get; set; }
        public string AdminPassword { get; set; }
        public string AdminPhone { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Role { get; set; }
    }
}
