//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital.Forensic.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCoC
    {
        public int FileID { get; set; }
        public Nullable<int> WID { get; set; }
        public string DCoCFileName { get; set; }
        public string DCoCFileExtension { get; set; }
        public string DCoCFileData { get; set; }
        public string DCoCFileDataEnc { get; set; }
    }
}
