//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital.Forensic.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string CapturedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isActivated { get; set; }
        public Nullable<bool> HasChangedPassword { get; set; }
        public string UserRole { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    }
}
