//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital.Forensic.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public int WID { get; set; }
        public string PublicKey { get; set; }
        public int NoOfActors { get; set; }
        public string GeneratedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
